//faketoken
export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImpvYW8iLCJlbWFpbCI6ImpvYW9AZW1haWwuY29tIiwiaWF0IjoxNzAwNjgyNjMwLCJleHAiOjE3MDA2ODQ0MzAsImF1ZCI6InVzZXJzIiwiaXNzIjoiZm9yZ2V0Iiwic3ViIjoiMSJ9.YxhdR1cyRucM4RtzEHoOm_RdlryogHhMldB-bi7M_WA';
